FILE=mem_bw_latency
all: $(FILE)
outline:
	pdflatex outline
$(FILE):
	pdflatex $(FILE)
	pdflatex $(FILE)
	# bibtex $(FILE)
	# bibtex $(FILE)
	# bibtex $(FILE)
	# pdflatex $(FILE)
	# pdflatex $(FILE)
clean:
	rm -f *~ *.log *.aux *.lof *.lot *.toc *.bbl *.blg *.loa *.out
allclean:
	rm -f *~ *.log *.aux *.lof *.lot *.toc *.bbl *.blg *.loa *.out *.dvi *.ps *.pdf 
