all:
	make -f Makefile.stream_triad
	make -f Makefile.stream_scale
	make -f Makefile.stream_rwo

clean:
	make -f Makefile.stream_triad clean
	make -f Makefile.stream_scale clean
	make -f Makefile.stream_rwo clean
